Add ci.yml

diff --git a/examples/Makefile b/examples/Makefile
--- a/examples/Makefile
+++ b/examples/Makefile
@@ -18,3 +18,14 @@ tidy-ci:
 
 gosec:
 	gosec ./...
+
+fmt-check:
+	# for the root module, check if files are formatted
+	@UNFORMATTED=$$(find . -name '*.go' -not -path './.data/*' -not -path './examples/*' -exec gofmt -l {} \;); \
+	if [ -n "$$UNFORMATTED" ]; then \
+		echo >&2 "ERROR: The following files are not formatted:"; \
+		echo "$$UNFORMATTED"; \
+		exit 1; \
+	fi
+	# then, for all child modules, use a module-managed `Makefile`
+	git ls-files '**/*go.mod' -z | xargs -0 -I{} bash -xc 'cd $$(dirname {}) && make fmt-check'
